version: '3'
services:
  web:
    build: .
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/edufintech_development
      - REDIS_URL=redis://redis:6379/1

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  bundle: 