# PostgreSQLの設定ファイル。バージョン9.3以上をサポート
#
# PostgreSQLドライバーのインストール方法:
#   gem install pg
# macOSでHomebrewを使用する場合:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# Windowsの場合:
#   gem install pg
#       win32ビルドを選択
#       PostgreSQLをインストールし、binディレクトリをパスに追加
#
# Gemfileでの設定方法
# gem "pg"
#
# デフォルトの設定をdefaultブロックで定義
default: &default
  adapter: postgresql      # PostgreSQLアダプターを使用
  encoding: unicode        # 文字エンコーディングをUnicodeに設定
  # コネクションプーリングの詳細はRailsの設定ガイドを参照
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>  # 同時接続数の設定
  host: db                # データベースホスト名
  username: postgres      # データベースユーザー名
  password: password      # データベースパスワード

# 開発環境の設定
development:
  <<: *default           # デフォルト設定を継承
  database: edufintech_development  # 開発用データベース名

  # PostgreSQLに接続するためのロール設定
  # 追加のロールを作成する場合は `$ createuser --help` を参照
  # 空白の場合、PostgreSQLはデフォルトロールを使用
  #username: app

  # PostgreSQLロールに関連付けられたパスワード
  #password:

  # TCPソケットでの接続設定
  # デフォルトではクライアントがドメインソケットを使用するため省略
  # Windowsにはドメインソケットがないため、必要に応じて設定
  #host: localhost

  # サーバーが待ち受けるTCPポート（デフォルト: 5432）
  # 異なるポート番号を使用する場合は変更
  #port: 5432

  # スキーマ検索パス
  #schema_search_path: myapp,sharedapp,public

  # ログレベルの設定（重要度順）:
  #   debug5, debug4, debug3, debug2, debug1,
  #   log, notice, warning, error, fatal, panic
  # デフォルトは warning
  #min_messages: notice

# 警告: "test"として定義されたデータベースは
# rake実行時に開発用データベースから再生成される
# 開発環境や本番環境と同じデータベースを指定しないこと
test:
  <<: *default           # デフォルト設定を継承
  database: edufintech_test     # テスト用データベース名

# config/credentials.ymlと同様に、データベースパスワードなどの
# 機密情報をソースコードに保存してはいけない
# ソースコードが他者に見られた場合、データベースにアクセスされる危険がある
#
# 代わりに、アプリケーション起動時に環境変数として
# パスワードや接続URLを提供する。例:
#
#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
#
# DATABASE_URL環境変数が提供された場合、Railsは自動的に
# この設定ファイルの値と結合する
# 明示的に接続URL環境変数を指定することも可能:
#
#   production:
#     url: <%= ENV["MY_APP_DATABASE_URL"] %>
#
# データベース接続設定の詳細については以下を参照:
# https://guides.rubyonrails.org/configuring.html#configuring-a-database
#
# 本番環境の設定
production:
  # プライマリデータベースの設定
  primary: &primary_production
    <<: *default         # デフォルト設定を継承
    database: app_production  # 本番用データベース名
    username: app        # 本番環境用ユーザー名
    password: <%= ENV["APP_DATABASE_PASSWORD"] %>  # 環境変数からパスワードを取得

  # キャッシュ用データベース設定
  cache:
    <<: *primary_production  # 本番環境のプライマリ設定を継承
    database: app_production_cache  # キャッシュ用データベース名
    migrations_paths: db/cache_migrate  # キャッシュ用マイグレーションパス

  # キュー用データベース設定
  queue:
    <<: *primary_production  # 本番環境のプライマリ設定を継承
    database: app_production_queue  # キュー用データベース名
    migrations_paths: db/queue_migrate  # キュー用マイグレーションパス

  # Action Cable用データベース設定
  cable:
    <<: *primary_production  # 本番環境のプライマリ設定を継承
    database: app_production_cable  # Action Cable用データベース名
    migrations_paths: db/cable_migrate  # Action Cable用マイグレーションパス
